---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: NodePort 
  selector:
    app: sonatype-registry
  ports:
    - name: nexus-ui
      port: 8081
      targetPort: 8081
      nodePort: 30081 
    - name: nexus-registry
      port: 5043
      targetPort: 5043
      nodePort: 30043
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      volumes:
      - name: registry-vol-data
        persistentVolumeClaim:
          claimName: nexus-data-pvc
      - name: registry-vol
        persistentVolumeClaim:
          claimName: nexus-pvc
      containers:
      - image: sonatype/nexus3
        name: nexus
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: registry-vol-data
          mountPath: /nexus-data
        - name: registry-vol
          mountPath: /opt/sonatype/nexus/etc/ssl
